spring.application.name=ats_springboot_mongodb
server.port=8081
spring.mongodb.uri=mongodb://trainingUser:trainingPwd@localhost:27017/ats_db?authSource=admin


# Cloudinary Configuration
# Đăng ký tại https://cloudinary.com và lấy thông tin bên dưới
cloudinary.cloud-name=dxg7ugmuh
cloudinary.api-key=433454136711868
cloudinary.api-secret=jmU-m5mPNbIeESDTXwDd_CaCkrc

# File upload size limit (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
